# Generated by Django 4.1.2 on 2022-12-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_messages_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='messeger',
            new_name='messager',
        ),
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(max_length=10000),
        ),
    ]
